export const TRANSACTION_LIST_REQUEST = "TRANSACTION_LIST_REQUEST";
export const TRANSACTION_LIST_SUCCESS = "TRANSACTION_LIST_SUCCESS";
export const TRANSACTION_LIST_FAIL = "TRANSACTION_LIST_FAIL";

export const TRANSACTION_DETAILS_REQUEST = "TRANSACTION_DETAILS_REQUEST";
export const TRANSACTION_DETAILS_SUCCESS = "TRANSACTION_DETAILS_SUCCESS";
export const TRANSACTION_DETAILS_FAIL = "TRANSACTION_DETAILS_FAIL";

export const TRANSACTION_CREATE_REQUEST = "TRANSACTION_CREATE_REQUEST";
export const TRANSACTION_CREATE_SUCCESS = "TRANSACTION_CREATE_SUCCESS";
export const TRANSACTION_CREATE_FAIL = "TRANSACTION_CREATE_FAIL";

export const TRANSACTION_EDIT_REQUEST = "TRANSACTION_EDIT_REQUEST";
export const TRANSACTION_EDIT_SUCCESS = "TRANSACTION_EDIT_SUCCESS";
export const TRANSACTION_EDIT_FAIL = "TRANSACTION_EDIT_FAIL";

export const TRANSACTION_DELETE_REQUEST = "TRANSACTION_DELETE_REQUEST";
export const TRANSACTION_DELETE_SUCCESS = "TRANSACTION_DELETE_SUCCESS";
export const TRANSACTION_DELETE_FAIL = "TRANSACTION_DELETE_FAIL";
